using System.Runtime.CompilerServices;

[assembly: InternalsVisibleTo("ScenarioModelling.Annotations")]
[assembly: InternalsVisibleTo("ScenarioModelling.CodeHooks")]
[assembly: InternalsVisibleTo("ScenarioModelling.CodeHooks.Tests")]
[assembly: InternalsVisibleTo("ScenarioModelling.CoreObjects")]
[assembly: InternalsVisibleTo("ScenarioModelling.Execution")]
[assembly: InternalsVisibleTo("ScenarioModelling.Execution.Tests")]
[assembly: InternalsVisibleTo("ScenarioModelling.Exhaustiveness")]
[assembly: InternalsVisibleTo("ScenarioModelling.Exhaustiveness.Tests")]
[assembly: InternalsVisibleTo("ScenarioModelling.Mocks")]
[assembly: InternalsVisibleTo("ScenarioModelling.Mocks.Tests")]
[assembly: InternalsVisibleTo("ScenarioModelling.Serialisation")]
[assembly: InternalsVisibleTo("ScenarioModelling.Serialisation.Tests")]
[assembly: InternalsVisibleTo("ScenarioModelling.Tools")]
[assembly: InternalsVisibleTo("ScenarioModelling.Tools.Tests")]