////Generated by the GOLD Parser Builder

//using System.IO;
//using System.Windows.Forms;

//class MyParser
//{
//    private GOLD.Parser parser = new GOLD.Parser(); 

//    private enum SymbolIndex
//    {

//    }

//    private enum ProductionIndex
//    {

//    }

//    public object program;     //You might derive a specific object

//    public void Setup()
//    {
//        //This procedure can be called to load the parse tables. The class can
//        //read tables using a BinaryReader.

//        parser.LoadTables(Path.Combine(Application.StartupPath, "grammar.egt"));
//    }

//    public bool Parse(TextReader reader)
//    {
//        //This procedure starts the GOLD Parser Engine and handles each of the
//        //messages it returns. Each time a reduction is made, you can create new
//        //custom object and reassign the .CurrentReduction property. Otherwise, 
//        //the system will use the Reduction object that was returned.
//        //
//        //The resulting tree will be a pure representation of the language 
//        //and will be ready to implement.

//        GOLD.ParseMessage response; 
//        bool done;                      //Controls when we leave the loop
//        bool accepted = false;          //Was the parse successful?

//        parser.Open(reader);
//        parser.TrimReductions = false;  //Please read about this feature before enabling  

//        done = false;
//        while (!done)
//        {
//            response = parser.Parse();

//            switch (response)
//            {
//                case GOLD.ParseMessage.LexicalError:
//                    //Cannot recognize token
//                    done = true;
//                    break;

//                case GOLD.ParseMessage.SyntaxError:
//                    //Expecting a different token
//                    done = true;
//                    break;

//                case GOLD.ParseMessage.Reduction:
//                    //Create a customized object to store the reduction

//                    parser.CurrentReduction = CreateNewObject(parser.CurrentReduction as GOLD.Reduction);
//                    break;

//                case GOLD.ParseMessage.Accept:
//                    //Accepted!
//                    //program = parser.CurrentReduction   //The root node!                 
//                    done = true;
//                    accepted = true;
//                    break;

//                case GOLD.ParseMessage.TokenRead:
//                    //You don't have to do anything here.
//                    break;

//                case GOLD.ParseMessage.InternalError:
//                    //INTERNAL ERROR! Something is horribly wrong.
//                    done = true;
//                    break;

//                case GOLD.ParseMessage.NotLoadedError:
//                    //This error occurs if the CGT was not loaded.                   
//                    done = true;
//                    break;

//                case GOLD.ParseMessage.GroupError: 
//                    //GROUP ERROR! Unexpected end of file
//                    done = true;
//                    break;
//            } 
//        } //while

//        return accepted;
//    }

//    private object CreateNewObject(GOLD.Reduction r)
//    { 
//        object result = null;

//        switch( (ProductionIndex) r.Parent.TableIndex)
//        {
//            case ProductionIndex.Nl_Newline:                 
//                // <nl> ::= NewLine <nl>
//                break;

//            case ProductionIndex.Nl_Newline2:                 
//                // <nl> ::= NewLine
//                break;

//            case ProductionIndex.Nlo_Newline:                 
//                // <nlo> ::= NewLine <nlo>
//                break;

//            case ProductionIndex.Nlo:                 
//                // <nlo> ::= 
//                break;

//            case ProductionIndex.String_Identifier:                 
//                // <String> ::= Identifier
//                break;

//            case ProductionIndex.String_Stringliteral:                 
//                // <String> ::= StringLiteral
//                break;

//            case ProductionIndex.Program:                 
//                // <Program> ::= <nlo> <Exp> <nlo>
//                break;

//            case ProductionIndex.Program2:                 
//                // <Program> ::= <nlo>
//                break;

//            case ProductionIndex.Exp:                 
//                // <Exp> ::= <AndOr Exp>
//                break;

//            case ProductionIndex.Andorexp_And:                 
//                // <AndOr Exp> ::= <AndOr Exp> AND <Is Exp>
//                break;

//            case ProductionIndex.Andorexp_Ampamp:                 
//                // <AndOr Exp> ::= <AndOr Exp> '&&' <Is Exp>
//                break;

//            case ProductionIndex.Andorexp_Or:                 
//                // <AndOr Exp> ::= <AndOr Exp> OR <Is Exp>
//                break;

//            case ProductionIndex.Andorexp_Pipepipe:                 
//                // <AndOr Exp> ::= <AndOr Exp> '||' <Is Exp>
//                break;

//            case ProductionIndex.Andorexp:                 
//                // <AndOr Exp> ::= <Is Exp>
//                break;

//            case ProductionIndex.Isexp_Eqeq:                 
//                // <Is Exp> ::= <Is Exp> '==' <Value Exp>
//                break;

//            case ProductionIndex.Isexp_Exclameq:                 
//                // <Is Exp> ::= <Is Exp> '!=' <Value Exp>
//                break;

//            case ProductionIndex.Isexp:                 
//                // <Is Exp> ::= <Value Exp>
//                break;

//            case ProductionIndex.Valueexp:                 
//                // <Value Exp> ::= <Value>
//                break;

//            case ProductionIndex.Valueexp2:                 
//                // <Value Exp> ::= <Function>
//                break;

//            case ProductionIndex.Valueexp3:                 
//                // <Value Exp> ::= <IsRelated>
//                break;

//            case ProductionIndex.Valueexp4:                 
//                // <Value Exp> ::= <IsNotRelated>
//                break;

//            case ProductionIndex.Valueexp_Lparen_Rparen:                 
//                // <Value Exp> ::= '(' <Exp> ')'
//                break;

//            case ProductionIndex.Function_Lparen_Rparen:                 
//                // <Function> ::= <String> '(' <Args> ')'
//                break;

//            case ProductionIndex.Args_Comma:                 
//                // <Args> ::= <Args> ',' <Exp>
//                break;

//            case ProductionIndex.Args:                 
//                // <Args> ::= <Exp>
//                break;

//            case ProductionIndex.Args2:                 
//                // <Args> ::= 
//                break;

//            case ProductionIndex.Isrelated_Minusquestiongt:                 
//                // <IsRelated> ::= <String> '-?>' <String>
//                break;

//            case ProductionIndex.Isrelated_Minusquestiongt_Colon:                 
//                // <IsRelated> ::= <String> '-?>' <String> ':' <String>
//                break;

//            case ProductionIndex.Isnotrelated_Minusexclamgt:                 
//                // <IsNotRelated> ::= <String> '-!>' <String>
//                break;

//            case ProductionIndex.Isnotrelated_Minusexclamgt_Colon:                 
//                // <IsNotRelated> ::= <String> '-!>' <String> ':' <String>
//                break;

//            case ProductionIndex.Value:                 
//                // <Value> ::= <CompositeValue>
//                break;

//            case ProductionIndex.Valuecomposite_Dot:                 
//                // <CompositeValue> ::= <CompositeValue> '.' <String>
//                break;

//            case ProductionIndex.Valuecomposite:                 
//                // <CompositeValue> ::= <String>
//                break;

//        }  //switch

//        return result;
//    }

//}; //MyParser
